spring:
  datasource:
    url: jdbc:mysql://121.251.255.96:3306/supermarket
    username: supermarket
    password: supermarket
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  http:
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
app:
  config:
    server: http://localhost:8082
server:
  port: 8082

